name: Build Docker Image

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ["8.0", "8.1", "8.2"]
    steps:
    - uses: actions/checkout@v3
    
    - name: Login into Github Docker Registery
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        file: "Dockerfile.${{ matrix.php }}"
        tags: ghcr.io/shyim/qodana-php:${{ matrix.php }}
        cache-from: type=gha,mode=max
        cache-to: type=gha,mode=max
