name: Build Docker Image

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Login into Github Docker Registery
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build the Docker image
      run: docker build -t ghcr.io/shyim/qodana-php .
      
    - name: Push image
      run: docker push ghcr.io/shyim/qodana-php
